# This is a basic workflow to help you get started with Actions
name: 'Linux Build'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: pnpm install
    - name: Check lint
      run: pnpm run lint
    - name: Build the app
      run: pnpm run electron:build

#    - name: Run headless unit test
#      uses: GabrielBB/xvfb-action@v1
#      with:
#        run: pnpm test

#    - name: Run headless e2e test
#      uses: GabrielBB/xvfb-action@v1
#      with:
#        run: pnpm run e2e

